DROP TABLE IF EXISTS CUSTOMER_INPUT;
DROP TABLE IF EXISTS CUSTOMER_OUTPUT;

CREATE TABLE CUSTOMER_INPUT (
  ID INTEGER NOT NULL auto_increment,
  FIRSTNAME CHARACTER(255) default NULL,
  LASTNAME CHARACTER(255) default NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER_OUTPUT (
  ID INTEGER NOT NULL auto_increment,
  FIRSTNAME CHARACTER(255) default NULL,
  LASTNAME CHARACTER(255) default NULL,
  PRIMARY KEY (ID)
);



# 오라클(12) 참고 일련번호 생성 참고
# CREATE SEQUENCE dept_seq START WITH 1;
#
# CREATE TABLE departments (
#                              ID           NUMBER(10)    DEFAULT dept_seq.nextval NOT NULL,
#                              DESCRIPTION  VARCHAR2(50)  NOT NULL);
#
# ALTER TABLE departments ADD (
#     CONSTRAINT dept_pk PRIMARY KEY (ID));